### ISSUE TITLE
provider "ns1" version attribute does not allow variables

### ISSUE THREAD

**Issue by chris-zenfolio** [terraform-providers/terraform-provider-ns1#103]
**### Terraform Version**
```hcl
$ terraform -v
Terraform v0.12.19
+ provider.ns1 v1.6.4
```
**### Affected Resource(s)**
`provider "ns1"` >> specifically the `version` attribute

**### Terraform Configuration Files**
_Note:  These two configuration blocks are normally in separate `.tf` files in our environment, but are combined here for readability.  This doesn't make a difference in functionality._
```hcl
variable "ns1_provider" {
    description = "These are all the values needed for the NS1 Provider block"
    default = {
            apikey                 = "SOME_API_KEY_VALUE_HERE"
            provider_version       = "1.6.4"
            api_endpoint           = "https://api.nsone.net/v1"  # default value
            ignore_ssl             = false                       # default value
            rate_limit_parallelism = 10                          # default value
    }
}

provider "ns1" {
    apikey                 = var.ns1_provider.apikey
    version                = var.ns1_provider.provider_version
    endpoint               = var.ns1_provider.api_endpoint
    ignore_ssl             = var.ns1_provider.ignore_ssl
    rate_limit_parallelism = var.ns1_provider.rate_limit_parallelism
```

**### Debug Output**
This is the failure observed when running `terraform init` with the `version` attribute interpolating a variable:
https://gist.github.com/chris-zenfolio/55955de18d22541a5387cda9806b8979

This is the success observed when running `terraform init` with the `version` attribute hard-coded:
https://gist.github.com/chris-zenfolio/b61c667647b0d7aff889ea2c06623e0d

This is the failure observed when running `terraform plan` (for example, if you started with a hard-coded value and changed to variable interpolation:
https://gist.github.com/chris-zenfolio/e9485923eda09d1df6470f3aeb7bd475

This is the success observed when running `terraform plan` after correcting the previous failure (by hard-coding the `version` attribute):
https://gist.github.com/chris-zenfolio/4a8702ef32aad730449becc950e8cf76

**### Panic Output**
No panic output

**### Expected Behavior**
The `version` attribute would interpolate the variable, just like for all the other attributes in the provider block.

**### Actual Behavior**
Both terraform init and terraform plan fail with a hard error "Variable not allowed."  This requires hard-coding that attribute.  We are only trying to hard-code values in a variables file (i.e., `variables.tf` or `terraform.tfvars`).  Error output:

```hcl
Error: Variables not allowed

  on providers.tf line 19, in provider "ns1":
  19:     version                = var.ns1_provider.provider_version

Variables may not be used here.
```

**### Steps to Reproduce**
Please list the steps required to reproduce the issue, for example:
1) Use the variable and provider configuration above
2) Run `terraform init` or `terraform apply`

**### Important Factoids**
Workaround for this bug:
```hcl
provider "ns1" {
    apikey                 = var.ns1_provider.apikey
    version                = "1.6.4" . # or whatever version number it should be
    endpoint               = var.ns1_provider.api_endpoint
    ignore_ssl             = var.ns1_provider.ignore_ssl
    rate_limit_parallelism = var.ns1_provider.rate_limit_parallelism
```

**### References**
No references.

// EDIT: 1/10/2020: Corrected grammatical error in Expected Behavior section.

**Comment by rupa** [comment]
Hi, thanks for the report.

I don't think this is specific to our provider. I can replicate with e.g. the digital ocean provider, so it looks to be built-in behavior.

Not sure why variables are disallowed for the version field, but it's not something we chose or configured. I'm definitely interested in the rationale behind this - it doesn't seem harmful to allow, so I wonder what the story is.

**Comment by chris-zenfolio** [comment]
Interesting!  I hadn't tried other providers.  Somehow, I'm not completely surprised, as I didn't see anything obvious when trying to look through the source code on here.

Feel free to close this at your convenience.

**Comment by rupa** [comment]
cool, we'll close it out. was news to me too, but we did find more information about this:

There's an issue in TF core for this - according to that it’s because providers need to be resolved at init time and cannot dynamically change, so setting this via variable would be bad: 

https://github.com/hashicorp/terraform/issues/17211

That said, I think you’re now supposed to set your required versions in a required_providers block inside a terraform block, instead of in the provider’s block, according to last para of https://www.terraform.io/docs/configuration/providers.html#provider-versions. Our provider docs should probably call that out as opposed to just the field in the provider block.

(but looks like the `required_providers` block explicitly disallows variable too though ...)
