### ISSUE TITLE
How to obfuscate the API key?

### ISSUE THREAD

**Issue by poblahblahblah** [terraform-providers/terraform-provider-ns1#14]
### Terraform Version
Terraform v0.11.1, using master (sha: 68489a27b98470af82dcb992b88bd14b2f52061b) of the ns1 provider.

### Affected Resource(s)
Please list the resources as a list, for example:
- ns1_api_key

### Terraform Configuration Files
```hcl
provider "ns1" {
  apikey = "${var.prod_ns1_api_key}"
  version             = "8.4.0"
}

terraform {
  backend "s3" {
    bucket = "company-terraform-state"
    key    = "external-dns/zones/foobar.org.tfstate"
    region = "us-east-1"
  }
}

resource "ns1_zone" "foobar_org" {
  zone = "${var.zone_name}"
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
There should be a way to specify an API key that is not committed to a VCS. It would be very preferable if the provider could read a file on the file system or it could read an environment variable.

### Actual Behavior

```
Error: variable "prod_ns1_api_key": default may not contain interpolations
```

### Steps to Reproduce
1. `terraform init`

### Important Factoids
N/A

### References
N/A

**Comment by ChrisMcKee** [comment]
You need to specify variables ala

```
variable "ns1_apikey" {
}

provider "ns1" {
  apikey = "${var.ns1_apikey}"
}
```

Which can be specified on command line or env etc (see the docs linked below) 
https://www.terraform.io/intro/getting-started/variables.html

I'm using this provider heavily so I can vouch that supplying the key via vars works fine

**Comment by poblahblahblah** [comment]
Gah, I see what I did wrong. Thanks for the pro tip - closing.
