### ISSUE TITLE
ns1_record refresh does not support resources disappearing

### ISSUE THREAD

**Issue by stmarier** [terraform-providers/terraform-provider-ns1#26]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
```
Terraform v0.11.6
+ provider.ns1 v1.0.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- ns1_record
- possibly more

### Terraform Configuration Files
```
resource "ns1_record" "a___apex" {
     zone = "${var.zone_name}"
     domain = "${var.zone_name}"
     type = "ALIAS"
     ttl = 3600

     answers = {
          answer = "example.com."
     }
}
```

### Expected Behavior
On refresh, if a record does not exist, TF+ns1 should want to create it again.

### Actual Behavior
On refresh (as part of `terraform plan`), the following errors are logged:
```
Error: Error refreshing state: 2 error(s) occurred:
* ns1_record.cname___www: 1 error(s) occurred:
* ns1_record.cname___www: ns1_record.cname___www: record does not exist
* ns1_record.a___example: 1 error(s) occurred:
* ns1_record.a___example: ns1_record.a___apex: record does not exist
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. run a `terraform apply` that creates an ns1_record resource
2. from the web interface, delete the record
3. run a `terraform plan`

### Important Factoids
This doesn't seem like a terraform specific issue, I took a quick look (approx 30 seconds) at the resource in this repo and it looks like it's just mapping API output and returning it?  It seems like `RecordRead` could be extended to catch "record doesn't exist" errors and instead signal that the record should be created, instead of exiting.

**Comment by scaldwell-alienvault** [comment]
I've confirmed this bug.

I see why it happens.  The "Important Factoids" are spot-on!
Adding this comment so I can find this later tonight along with another bug that is plaguing me so a pull request can be put together.

**Suggested solution:**
1. Send POST to update records (as it seems to be doing).
2. On failure, if message "Not Found" is returned, submit PUT to create new record with expected state.

**Comment by sam-caldwell** [comment]
Solution proposed in pull request https://github.com/terraform-providers/terraform-provider-ns1/pull/90
