### ISSUE TITLE
mx record import error

### ISSUE THREAD

**Issue by tenzone** [terraform-providers/terraform-provider-ns1#29]
### Terraform Version
0.11.7

### Affected Resource(s)
ns1_resource of MX type

### Terraform Configuration Files
```
terraformimport ns1_record.example_mx example.com/example.com/MX
```

### Expected Behavior
the record should be imported and managed by terraform

### Actual Behavior
```
ns1_record.example_mx: Importing from ID "example.com/example.com/MX"...
ns1_record.example_mx: Import complete!
  Imported ns1_record (ID: abote.com/example.com/MX)
ns1_record.example_mx: Refreshing state... (ID: example.com/example.com/MX)

Error: ns1_record.example_mx (import id: example.com/example.com/MX): 1 error(s) occurred:

* import ns1_record.example_mx result: example.com/example.com/MX: ns1_record.example_mx: json: cannot unmarshal number into Go struct field Answer.answer of type string
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. import the MX record

**Comment by tenzone** [comment]
I am also having this issue with importing an SRV record, terraform is looking for a string and receiving an integer from the api, it seems

**Comment by ionigman** [comment]
The API returns an array of two strings for MX records:

{
            "answer" : [ 
                "10", 
                "mail.example.com."
            ],
            "_id" : ObjectId("5b0fffc0a632f6000897ff01")
        }

**Comment by tenzone** [comment]
@ionigman interesting, when i query  the API, i see one integer, one string
```
{
      "answer": [
        10,
        "mail.example.com"
      ],
```

ok,   when i create an mx via terraform, the return is
```
{
      "answer": [
        "10",
        "mail.example.com"
```

so could it be that records created via terraform are terraform compliant, but records created through the console are not?
