### ISSUE TITLE
Unable to import MX record

### ISSUE THREAD

**Issue by brycekahle** [terraform-providers/terraform-provider-ns1#36]
Attempting to import an MX record results in a json marshaling error. I believe this is due to the priority data in the answer being a number. Ex:
`"answer":[10, "mail2.example.com"]`

### Terraform Version
```
Terraform v0.11.7
+ provider.ns1 v1.0.0
```

### Affected Resource(s)
- ns1_record

### Terraform Configuration Files
```
resource "ns1_zone" "example_com" {
  zone    = "example.com"
}

resource "ns1_record" "example_com_MX" {
  zone   = "${ns1_zone.example_com.zone}"
  domain = "example.com"
  type   = "MX"

  answers {
    answer = "10 mx.example.com"
  }
}
```

### Expected Behavior
MX record is imported.

### Actual Behavior
```
json: cannot unmarshal number into Go struct field Answer.answer of type string
```

### Steps to Reproduce
1. `terraform import ns1_record.example_com_MX 'example.com/example.com/MX'`

**Comment by liebman** [comment]
I have seen this too and its because NS1 splits the priority from the domain in the answer in their API and do not enforce the type for the priority.  I chatted with NS1 support and the answer was: 

> The API is reading back what we have stored in the database.
> 
> The likely cause is that on creation the records in question used either different methods for import or creation (portal vs import vs API) or may have been created at different times.
> 
> As far as I am aware, we do not enforce a type restriction on the priority. It can be stored as either a string or an integer in the system.
> 
> As a workaround for you, I'd suggest casting the priority to the datatype needed on retrieval to avoid issues.
> 
> I will create a ticket documenting this issue with our dev team, but due to prioritization, I can't say when (or even if) it will be addressed within the code base.

**Comment by lcarstensen** [comment]
Also see https://github.com/terraform-providers/terraform-provider-ns1/issues/29

**Comment by ricbartm** [comment]
Yeah, I did what @tenzone did in https://github.com/terraform-providers/terraform-provider-ns1/issues/29 and it worked for me. Other MX records that were created recently and imported were imported successfully. I think this issue no longer applies.

**Comment by rupa** [comment]
Hi, yep, this has been fixed up and I can confirm it works with the current version of our provider. Sorry I didn't notice this was one of the issues that was affected by these recent changes.

**Comment by rupa** [comment]
Also, MX handling should be working now without any special workarounds (there's better support for this record type in the underlying SDK)
