### ISSUE TITLE
NS1 record to validate aws_acm_certificate fails - trailing dot

### ISSUE THREAD

**Issue by namachieli** [terraform-providers/terraform-provider-ns1#38]
### Terraform Version
`Terraform v0.11.10`
`Provider: NS1 v1.0.0`
`Provider: AWS v1.39.0`

### Affected Resource(s)
 - ns1_record
 - aws_acm_certificate

### Terraform Configuration Files
```hcl
resource "ns1_record" "cert_validation" {
  zone                      = "${var.ns1-zone}"
  domain                    = "${aws_acm_certificate.certificate.domain_validation_options.0.resource_record_name}"
  type                      = "${aws_acm_certificate.certificate.domain_validation_options.0.resource_record_type}"
  ttl                       = 60
  answers = {
    answer                  = "${aws_acm_certificate.certificate.domain_validation_options.0.resource_record_value}"
  }
}
```

### Debug Output
```
* ns1_record.cert_validation_0: 1 error(s) occurred:

* ns1_record.cert_validation_0: PUT https://api.nsone.net/v1/zones/<zone>/_a2f[...]3cd.<subdomain>.<domain><zone>..<zone>/CNAME: 400 "_a2f[...]3cd.<subdomain>.<domain><zone>..<zone>" not a valid domain in <zone>
```

### Expected Behavior
The record should have been created based on the output of `aws_acm_certificate`

### Actual Behavior
The output from `aws_acm_certificate` includes the trailing dot in the `name`. Acceptable inputs for `ns1_record` are either an FQDN including the zone (no trailing dot), or just the resource record and the zone will be appended automatically. When a trailing dot is included at the end the zone is appended, so you end up with `<resource><zone>..<zone>` which NS1 api fails to accept (correctly).

### Steps to Reproduce
 - Have an `aws_acm_certificate` with one or more `subject_alternative_names`
 - Create an NS1 DNS record to complete validation using `aws_acm_certificate.certificate.domain_validation_options.0.resource_record_name` as the input for `ns1_record.record.domain`

### Current workaround
Doing a `replace()` on the interpolated string allows for proper formatting. (replaces trailing dot with nothing)
```
"${replace(aws_acm_certificate.certificate.domain_validation_options.0.resource_record_name, "/\\.$/", "")}"
```

**Comment by scaldwell-alienvault** [comment]
I can see why this happens.

1. Let's look at lines 37-50 of terraform-provider-ns1/vendor/gopkg.in/ns1/ns1-go.v2/rest/model/dns/record.go.  Here we see that our test to format the string is checking if our domain ends with zone.  But if it ends with zone<dot> it would fail this.

2. I reproduced the problem on a smaller scale in the following code:


`
package main

import (
	"fmt"
	"strings"
)
func main() {
	d:="agent.google.com."
	z:="google.com"
	if !strings.HasSuffix(d,z){
		d+=z
	}
	fmt.Println(d)
}
`
The solution looks something like this:
`
package main

import (
	"fmt"
	"strings"
)

func removeTrailingDot(s string) string{
	if strings.HasSuffix(s,"."){
		s=s[0:len(s)-1]
	}
	return s
}
func main() {
	d:="agent.google.com."
	z:="google.com"
	d=removeTrailingDot(d)
	if !strings.HasSuffix(d,z){
		d+=z
	}
	d=removeTrailingDot(d)
	fmt.Println(d)
}
`
Note that I scrub trailing dots from the domain and zone before and after operations.  That's probably a bit more than the minimum needed to solve the problem, but it ensures these HTTP/400 responses go away.

A pull request will be submitted shortly.

**Comment by sam-caldwell** [comment]
I have created an issue in ns1/ns1-go to close the loop between this project and that project, where the solution will be implemented.   See https://github.com/ns1/ns1-go/issues/79.

**Comment by sam-caldwell** [comment]
A pull request is submitted to address this issue.  See https://github.com/ns1/ns1-go/pull/80

**Comment by Zach-Johnson** [comment]
Validation and appropriate documentation has been added for this on this PR: https://github.com/terraform-providers/terraform-provider-ns1/pull/97

**Comment by Zach-Johnson** [comment]
The PR mentioned above has been merged and released so I'm closing this issue.
