### ISSUE TITLE
ns1_record regions attribute is missing required meta and feeds properties

### ISSUE THREAD

**Issue by dbeckham** [terraform-providers/terraform-provider-ns1#5]
The `ns1_record` resource's `regions` config is missing the `meta` and `feeds` properties.  These two properties completely define what a region is and how it is used. Without them, there is absolutely no reason to define a region, nor assign a region to an `answers` config.

This also causes several filter types to be pointless as they require meta data attached to answers in order to function.

**Comment by alistanis** [comment]
Changes for this were pushed in #11, again, sorry for the wait @dbeckham
