### ISSUE TITLE
cant create mx record

### ISSUE THREAD

**Issue by dolvany** [terraform-providers/terraform-provider-ns1#61]
### Terraform Version
Terraform v0.11.14
+ provider.ns1 v1.5.0

### Affected Resource(s)
- ns1_record

### Terraform Configuration Files
```
{
  "resource": {
    "ns1_record": {
      "foo": {
        "zone": "${ns1_zone.foo.zone}",
        "domain": "foo.com",
        "type": "MX",
        "ttl": 3600,
        "answers": [
          {
            "answer": "10 mail.foo.com"
          }
        ]
      }
    }
  }
}
```

### Expected Behavior
MX record created and resource added to tf state.

### Actual Behavior
MX record created and resource not added to tf state.

### Steps to Reproduce
Record is created, but an error is encountered before the resource is added to the tf state.
```
$ terraform apply --target=ns1_record.foo
	* ns1_record.foo: json: cannot unmarshal number into Go struct field Answer.answer of type string
```
Record exists, but resource does not exist in tf state.
```
$ terraform state show ns1_record.foo
$
```
Subsequent tf apply encounters an error due to missing state.
```
$ terraform apply --target=ns1_record.foo
	* ns1_record.foo: record already exists
```

**Comment by mburtless** [comment]
Old behavior has been restored in the API and I am no longer able to recreate this issue when creating new MX records via Terraform.  I'm going to close out this issue, but please reopen or open a new issue if you are still experiencing this.
