### ISSUE TITLE
Plan generates phantom changes to apply (failed permission inheritance?)

### ISSUE THREAD

**Issue by oogali** [terraform-providers/terraform-provider-ns1#84]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
```
Terraform v0.12.12
+ provider.ns1 v1.6.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- ns1_user.test

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "ns1_team" "test-team" {
  name = "test-team"

  dns_view_zones = true
  dns_manage_zones = true
  dns_zones_allow = [
    "t.testing.net",
  ]
  dns_zones_deny = []
  data_push_to_datafeeds = true
  data_manage_datasources = true
  data_manage_datafeeds = true

  account_manage_users = false
  account_manage_payment_methods = false
  account_manage_plan = false
  account_manage_teams = false
  account_manage_apikeys = false
  account_manage_account_settings = false
  account_view_activity_log = true
  account_view_invoices = false

  monitoring_manage_lists = true
  monitoring_manage_jobs = true
  monitoring_view_jobs = true
}

resource "ns1_user" "test" {
  name = "IaC Testing"
  username = "testing_org"
  email = "testing@example.com"
  notify = {
    billing = false
  }
  teams = [ns1_team.test-team.id]
}
```

### Debug Output
https://gist.github.com/oogali/1e230933e1200aa2aeb50d249830a509

### Panic Output
No panic produced.

### Expected Behavior
No changes/updates should be required as the user resource hasn't changed.

### Actual Behavior
Every time a plan is run, the NS1 provider wishes to modify attributes inherited from the team permissions, and set them to null.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. `terraform apply`

### Important Factoids
No important facts to mention here.

### References
No references.

**Comment by mburtless** [comment]
Hi @oogali - I think the core issue here is the same as #15.

Essentially, user is inheriting permissions from team within NS1 as intended, but the config of the user resource makes Terraform think that the inherited permissions should be unset, causing a diff.

#56 (slightly out of date, at the moment) would resolve this issue by introducing a new team member resource, which would expressly be used when creating a user that should inherit permissions from a team.  Would love to get your feedback on that proposed solution, if you have a chance.
