### ISSUE TITLE
Error Strings contain capital letters or punctuation

### ISSUE THREAD

**Issue by sam-caldwell** [terraform-providers/terraform-provider-ns1#92]
### Terraform Version
`
Terraform v0.11.6
+ provider.ns1 v1.6.0
`

### Affected Resource(s)
Issue exists throughout the code base.

### Terraform Configuration Files
* N/A

### Debug Output
* N/A

### Panic Output
* N/A

### Expected Behavior

> Error strings should not be capitalized (unless beginning with proper nouns or acronyms) or end with punctuation, since they are usually printed following other context. That is, use fmt.Errorf("something bad") not fmt.Errorf("Something bad"), so that log.Printf("Reading %s: %v", filename, err) formats without a spurious capital letter mid-message. This does not apply to logging, which is implicitly line-oriented and not combined inside other messages.
-- Quoting [Golang Code Review Comments](https://github.com/golang/go/wiki/CodeReviewComments#error-strings)

### Actual Behavior
1. My IDE complains about various strings used in the code base, distracting me from debugging.

### Steps to Reproduce
N/A

### Important Factoids
If I've got the time to submit this issue, I've got the time to send a Pull Request and contribute to the community.  It's in my queue of stuff for free time.

**Comment by rupa** [comment]
Closed by #93
